export const weightUnits = [
   {
      id: 0,
      label: "lb",
      value: "pound",
      plural: "pounds",
   },
   {
      id: 1,
      label: "kg",
      value: "kilogram",
      plural: "kilograms",
   },
];

export const distanceUnits = [
   {
      id: 0,
      label: "mi",
      value: "mile",
      plural: "miles",
   },
   {
      id: 1,
      label: "yd",
      value: "yard",
      plural: "yards",
   },
   {
      id: 2,
      label: "ft",
      value: "foot",
      plural: "feet",
   },
   {
      id: 3,
      label: "m",
      value: "meter",
      plural: "meters",
   },
   {
      id: 4,
      label: "km",
      value: "kilometer",
      plural: "kilometers",
   },
];

export const exercises = [
   { id: 0, group: "Chest", name: "Assisted Dip" },
   { id: 1, group: "Chest", name: "Band-Assisted Bench Press" },
   { id: 2, group: "Chest", name: "Bar Dip" },
   { id: 3, group: "Chest", name: "Bench Press" },
   { id: 4, group: "Chest", name: "Bench Press Against Band" },
   { id: 5, group: "Chest", name: "Board Press" },
   { id: 6, group: "Chest", name: "Cable Chest Press" },
   { id: 7, group: "Chest", name: "Close-Grip Bench Press" },
   { id: 8, group: "Chest", name: "Close-Grip Feet-Up Bench Press" },
   { id: 9, group: "Chest", name: "Decline Bench Press" },
   { id: 10, group: "Chest", name: "Decline Push-Up" },
   { id: 11, group: "Chest", name: "Dumbbell Chest Fly" },
   { id: 12, group: "Chest", name: "Dumbbell Chest Press" },
   { id: 13, group: "Chest", name: "Dumbbell Decline Chest Press" },
   { id: 14, group: "Chest", name: "Dumbbell Floor Press" },
   { id: 15, group: "Chest", name: "Dumbbell Pullover" },
   { id: 16, group: "Chest", name: "Feet-Up Bench Press" },
   { id: 17, group: "Chest", name: "Floor Press" },
   { id: 18, group: "Chest", name: "Incline Bench Press" },
   { id: 19, group: "Chest", name: "Incline Dumbbell Press" },
   { id: 20, group: "Chest", name: "Incline Push-Up" },
   { id: 21, group: "Chest", name: "Kettlebell Floor Press" },
   { id: 22, group: "Chest", name: "Kneeling Incline Push-Up" },
   { id: 23, group: "Chest", name: "Kneeling Push-Up" },
   { id: 24, group: "Chest", name: "Machine Chest Fly" },
   { id: 25, group: "Chest", name: "Machine Chest Press" },
   { id: 26, group: "Chest", name: "Pec Deck" },
   { id: 27, group: "Chest", name: "Pin Bench Press" },
   { id: 28, group: "Chest", name: "Push-Up" },
   { id: 29, group: "Chest", name: "Push-Up Against Wall" },
   { id: 30, group: "Chest", name: "Push-Ups With Feet in Rings" },
   { id: 31, group: "Chest", name: "Resistance Band Chest Fly" },
   { id: 32, group: "Chest", name: "Ring Dip" },
   { id: 33, group: "Chest", name: "Smith Machine Bench Press" },
   { id: 34, group: "Chest", name: "Smith Machine Incline Bench Press" },
   { id: 35, group: "Chest", name: "Smith Machine Reverse Grip Bench Press" },
   { id: 36, group: "Chest", name: "Standing Cable Chest Fly" },
   { id: 37, group: "Chest", name: "Standing Resistance Band Chest Fly" },
   { id: 38, group: "Shoulder", name: "Arnold Press" },
   { id: 39, group: "Shoulder", name: "Band External Shoulder Rotation" },
   { id: 40, group: "Shoulder", name: "Band Internal Shoulder Rotation" },
   { id: 41, group: "Shoulder", name: "Band Pull-Apart" },
   { id: 42, group: "Shoulder", name: "Banded Face Pull" },
   { id: 43, group: "Shoulder", name: "Barbell Front Raise" },
   { id: 44, group: "Shoulder", name: "Barbell Rear Delt Row" },
   { id: 45, group: "Shoulder", name: "Barbell Upright Row" },
   { id: 46, group: "Shoulder", name: "Behind the Neck Press" },
   { id: 47, group: "Shoulder", name: "Cable Internal Shoulder Rotation" },
   { id: 48, group: "Shoulder", name: "Cable Front Raise" },
   { id: 49, group: "Shoulder", name: "Cable Lateral Raise" },
   { id: 50, group: "Shoulder", name: "Cable Rear Delt Row" },
   { id: 51, group: "Shoulder", name: "Cuban Press" },
   { id: 52, group: "Shoulder", name: "Devils Press" },
   { id: 53, group: "Shoulder", name: "Dumbbell Front Raise" },
   {
      id: 54,
      group: "Shoulder",
      name: "Dumbbell Horizontal Internal Shoulder Rotation",
   },
   {
      id: 55,
      group: "Shoulder",
      name: "Dumbbell Horizontal External Shoulder Rotation",
   },
   { id: 56, group: "Shoulder", name: "Dumbbell Lateral Raise" },
   { id: 57, group: "Shoulder", name: "Dumbbell Rear Delt Row" },
   { id: 58, group: "Shoulder", name: "Dumbbell Shoulder Press" },
   { id: 59, group: "Shoulder", name: "Face Pull" },
   { id: 60, group: "Shoulder", name: "Front Hold" },
   { id: 61, group: "Shoulder", name: "Handstand Push-Up" },
   { id: 62, group: "Shoulder", name: "Jerk" },
   { id: 63, group: "Shoulder", name: "Kettlebell Halo" },
   { id: 64, group: "Shoulder", name: "Landmine Press" },
   {
      id: 65,
      group: "Shoulder",
      name: "Lying Dumbbell External Shoulder Rotation",
   },
   {
      id: 66,
      group: "Shoulder",
      name: "Lying Dumbbell Internal Shoulder Rotation",
   },
   { id: 67, group: "Shoulder", name: "Machine Lateral Raise" },
   { id: 68, group: "Shoulder", name: "Machine Shoulder Press" },
   { id: 69, group: "Shoulder", name: "Monkey Row" },
   { id: 70, group: "Shoulder", name: "One-Arm Landmine Press" },
   { id: 71, group: "Shoulder", name: "Overhead Press" },
   { id: 72, group: "Shoulder", name: "Plate Front Raise" },
   { id: 73, group: "Shoulder", name: "Power Jerk" },
   { id: 74, group: "Shoulder", name: "Push Press" },
   { id: 75, group: "Shoulder", name: "Reverse Cable Flyes" },
   { id: 76, group: "Shoulder", name: "Reverse Dumbbell Flyes" },
   { id: 77, group: "Shoulder", name: "Reverse Machine Fly" },
   { id: 78, group: "Shoulder", name: "Seated Dumbbell Shoulder Press" },
   { id: 79, group: "Shoulder", name: "Seated Barbell Overhead Press" },
   { id: 80, group: "Shoulder", name: "Seated Smith Machine Shoulder Press" },
   { id: 81, group: "Shoulder", name: "Snatch Grip Behind the Neck Press" },
   { id: 82, group: "Shoulder", name: "Squat Jerk" },
   { id: 83, group: "Shoulder", name: "Split Jerk" },
   { id: 84, group: "Shoulder", name: "Wall Walk" },
   { id: 85, group: "Bicep", name: "Barbell Curl" },
   { id: 86, group: "Bicep", name: "Barbell Preacher Curl" },
   { id: 87, group: "Bicep", name: "Bayesian Curl" },
   { id: 88, group: "Bicep", name: "Bodyweight Curl" },
   { id: 89, group: "Bicep", name: "Cable Crossover Bicep Curl" },
   { id: 90, group: "Bicep", name: "Cable Curl With Bar" },
   { id: 91, group: "Bicep", name: "Cable Curl With Rope" },
   { id: 92, group: "Bicep", name: "Concentration Curl" },
   { id: 93, group: "Bicep", name: "Drag Curl" },
   { id: 94, group: "Bicep", name: "Dumbbell Curl" },
   { id: 95, group: "Bicep", name: "Dumbbell Preacher Curl" },
   { id: 96, group: "Bicep", name: "Hammer Curl" },
   { id: 97, group: "Bicep", name: "Incline Dumbbell Curl" },
   { id: 98, group: "Bicep", name: "Machine Bicep Curl" },
   { id: 99, group: "Bicep", name: "Resistance Band Curl" },
   { id: 100, group: "Bicep", name: "Spider Curl" },
   { id: 101, group: "Bicep", name: "Zottman Curl" },
   { id: 102, group: "Tricep", name: "Barbell Standing Triceps Extension" },
   { id: 103, group: "Tricep", name: "Barbell Incline Triceps Extension" },
   { id: 104, group: "Tricep", name: "Barbell Lying Triceps Extension" },
   { id: 105, group: "Tricep", name: "Bench Dip" },
   { id: 106, group: "Tricep", name: "Crossbody Cable Triceps Extension" },
   { id: 107, group: "Tricep", name: "Close-Grip Push-Up" },
   { id: 108, group: "Tricep", name: "Dumbbell Lying Triceps Extension" },
   { id: 109, group: "Tricep", name: "Dumbbell Standing Triceps Extension" },
   { id: 110, group: "Tricep", name: "Overhead Cable Triceps Extension" },
   { id: 111, group: "Tricep", name: "Tate Press" },
   { id: 112, group: "Tricep", name: "Tricep Bodyweight Extension" },
   { id: 113, group: "Tricep", name: "Tricep Pushdown With Bar" },
   { id: 114, group: "Tricep", name: "Tricep Pushdown With Rope" },
   { id: 115, group: "Leg", name: "Air Squat" },
   { id: 116, group: "Leg", name: "Barbell Hack Squat" },
   { id: 117, group: "Leg", name: "Barbell Lunge" },
   { id: 118, group: "Leg", name: "Barbell Walking Lunge" },
   { id: 119, group: "Leg", name: "Belt Squat" },
   { id: 120, group: "Leg", name: "Body Weight Lunge" },
   { id: 121, group: "Leg", name: "Bodyweight Leg Curl" },
   { id: 122, group: "Leg", name: "Box Jump" },
   { id: 123, group: "Leg", name: "Box Squat" },
   { id: 124, group: "Leg", name: "Bulgarian Split Squat" },
   { id: 125, group: "Leg", name: "Chair Squat" },
   { id: 126, group: "Leg", name: "Dumbbell Lunge" },
   { id: 127, group: "Leg", name: "Dumbbell Squat" },
   { id: 128, group: "Leg", name: "Front Squat" },
   { id: 129, group: "Leg", name: "Glute Ham Raise" },
   { id: 130, group: "Leg", name: "Goblet Squat" },
   { id: 131, group: "Leg", name: "Hack Squat Machine" },
   { id: 132, group: "Leg", name: "Half Air Squat" },
   { id: 133, group: "Leg", name: "Hip Adduction Machine" },
   { id: 134, group: "Leg", name: "Jumping Lunge" },
   { id: 135, group: "Leg", name: "Landmine Hack Squat" },
   { id: 136, group: "Leg", name: "Landmine Squat" },
   { id: 137, group: "Leg", name: "Leg Curl On Ball" },
   { id: 138, group: "Leg", name: "Leg Extension" },
   { id: 139, group: "Leg", name: "Leg Press" },
   { id: 140, group: "Leg", name: "Lying Leg Curl" },
   { id: 141, group: "Leg", name: "Nordic Hamstring Eccentric" },
   { id: 142, group: "Leg", name: "One-Legged Leg Extension" },
   { id: 143, group: "Leg", name: "One-Legged Lying Leg Curl" },
   { id: 144, group: "Leg", name: "One-Legged Seated Leg Curl" },
   { id: 145, group: "Leg", name: "Pause Squat" },
   { id: 146, group: "Leg", name: "Pistol Squat" },
   { id: 147, group: "Leg", name: "Reverse Barbell Lunge" },
   { id: 148, group: "Leg", name: "Reverse Body Weight Lunge" },
   { id: 149, group: "Leg", name: "Reverse Dumbbell Lunge" },
   { id: 150, group: "Leg", name: "Romanian Deadlift" },
   { id: 151, group: "Leg", name: "Safety Bar Squat" },
   { id: 152, group: "Leg", name: "Seated Leg Curl" },
   { id: 153, group: "Leg", name: "Shallow Body Weight Lunge" },
   { id: 154, group: "Leg", name: "Side Lunges (Bodyweight)" },
   { id: 155, group: "Leg", name: "Smith Machine Bulgarian Split Squat" },
   { id: 156, group: "Leg", name: "Smith Machine Front Squat" },
   { id: 157, group: "Leg", name: "Smith Machine Squat" },
   { id: 158, group: "Leg", name: "Squat" },
   { id: 159, group: "Leg", name: "Step Up" },
   { id: 160, group: "Leg", name: "Zercher Squat" },
   { id: 161, group: "Leg", name: "Zombie Squat" },
   { id: 162, group: "Back", name: "Assisted Chin-Up" },
   { id: 163, group: "Back", name: "Assisted Pull-Up" },
   { id: 164, group: "Back", name: "Back Extension" },
   { id: 165, group: "Back", name: "Banded Muscle-Up" },
   { id: 166, group: "Back", name: "Barbell Row" },
   { id: 167, group: "Back", name: "Barbell Shrug" },
   { id: 168, group: "Back", name: "Block Clean" },
   { id: 169, group: "Back", name: "Block Snatch" },
   { id: 170, group: "Back", name: "Cable Close Grip Seated Row" },
   { id: 171, group: "Back", name: "Cable Wide Grip Seated Row" },
   { id: 172, group: "Back", name: "Chest to Bar" },
   { id: 173, group: "Back", name: "Chin-Up" },
   { id: 174, group: "Back", name: "Clean" },
   { id: 175, group: "Back", name: "Clean and Jerk" },
   { id: 176, group: "Back", name: "Close-Grip Lat Pulldown" },
   { id: 177, group: "Back", name: "Deadlift" },
   { id: 178, group: "Back", name: "Deficit Deadlift" },
   { id: 179, group: "Back", name: "Dumbbell Deadlift" },
   { id: 180, group: "Back", name: "Dumbbell Row" },
   { id: 181, group: "Back", name: "Dumbbell Shrug" },
   { id: 182, group: "Back", name: "Floor Back Extension" },
   { id: 183, group: "Back", name: "Good Morning" },
   { id: 184, group: "Back", name: "Gorilla Row" },
   { id: 185, group: "Back", name: "Hang Clean" },
   { id: 186, group: "Back", name: "Hang Power Clean" },
   { id: 187, group: "Back", name: "Hang Power Snatch" },
   { id: 188, group: "Back", name: "Hang Snatch" },
   { id: 189, group: "Back", name: "Inverted Row" },
   { id: 190, group: "Back", name: "Inverted Row with Underhand Grip" },
   { id: 191, group: "Back", name: "Jefferson Curl" },
   { id: 192, group: "Back", name: "Jumping Muscle-Up" },
   { id: 193, group: "Back", name: "Kettlebell Clean" },
   { id: 194, group: "Back", name: "Kettlebell Clean & Jerk" },
   { id: 195, group: "Back", name: "Kettlebell Clean & Press" },
   { id: 196, group: "Back", name: "Kettlebell Swing" },
   { id: 197, group: "Back", name: "Kroc Row" },
   { id: 198, group: "Back", name: "Lat Pulldown With Pronated Grip" },
   { id: 199, group: "Back", name: "Lat Pulldown With Supinated Grip" },
   { id: 200, group: "Back", name: "Muscle-Up (Bar)" },
   { id: 201, group: "Back", name: "Muscle-Up (Rings)" },
   { id: 202, group: "Back", name: "Neutral Close-Grip Lat Pulldown" },
   { id: 203, group: "Back", name: "One-Handed Cable Row" },
   { id: 204, group: "Back", name: "One-Handed Kettlebell Swing" },
   { id: 205, group: "Back", name: "One-Handed Lat Pulldown" },
   { id: 206, group: "Back", name: "Pause Deadlift" },
   { id: 207, group: "Back", name: "Pendlay Row" },
   { id: 208, group: "Back", name: "Power Clean" },
   { id: 209, group: "Back", name: "Power Snatch" },
   { id: 210, group: "Back", name: "Pull-Up" },
   { id: 211, group: "Back", name: "Pull-Up With a Neutral Grip" },
   { id: 212, group: "Back", name: "Rack Pull" },
   { id: 213, group: "Back", name: "Ring Pull-Up" },
   { id: 214, group: "Back", name: "Ring Row" },
   { id: 215, group: "Back", name: "Scap Pull-Up" },
   { id: 216, group: "Back", name: "Seal Row" },
   { id: 217, group: "Back", name: "Seated Machine Row" },
   { id: 218, group: "Back", name: "Single Leg Deadlift with Kettlebell" },
   { id: 219, group: "Back", name: "Smith Machine One-Handed Row" },
   { id: 220, group: "Back", name: "Snatch" },
   { id: 221, group: "Back", name: "Snatch Grip Deadlift" },
   { id: 222, group: "Back", name: "Stiff-Legged Deadlift" },
   { id: 223, group: "Back", name: "Straight Arm Lat Pulldown" },
   { id: 224, group: "Back", name: "Sumo Deadlift" },
   { id: 225, group: "Back", name: "T-Bar Row" },
   { id: 226, group: "Back", name: "Towel Row " },
   { id: 227, group: "Back", name: "Trap Bar Deadlift With High Handles" },
   { id: 228, group: "Back", name: "Trap Bar Deadlift With Low Handles" },
   { id: 229, group: "Glute", name: "Banded Side Kicks" },
   { id: 230, group: "Glute", name: "Cable Pull Through" },
   { id: 231, group: "Glute", name: "Cable Machine Hip Abduction" },
   { id: 232, group: "Glute", name: "Clamshells" },
   { id: 233, group: "Glute", name: "Cossack Squat" },
   { id: 234, group: "Glute", name: "Death March with Dumbbells" },
   { id: 235, group: "Glute", name: "Donkey Kicks" },
   { id: 236, group: "Glute", name: "Dumbbell Romanian Deadlift" },
   { id: 237, group: "Glute", name: "Dumbbell Frog Pumps" },
   { id: 238, group: "Glute", name: "Fire Hydrants" },
   { id: 239, group: "Glute", name: "Frog Pumps" },
   { id: 240, group: "Glute", name: "Glute Bridge" },
   { id: 241, group: "Glute", name: "Hip Abduction Against Band" },
   { id: 242, group: "Glute", name: "Hip Abduction Machine" },
   { id: 243, group: "Glute", name: "Hip Thrust" },
   { id: 244, group: "Glute", name: "Hip Thrust Machine" },
   { id: 245, group: "Glute", name: "Hip Thrust With Band Around Knees" },
   { id: 246, group: "Glute", name: "Lateral Walk With Band" },
   { id: 247, group: "Glute", name: "Machine Glute Kickbacks" },
   { id: 248, group: "Glute", name: "One-Legged Glute Bridge" },
   { id: 249, group: "Glute", name: "One-Legged Hip Thrust " },
   { id: 250, group: "Glute", name: "Reverse Hyperextension" },
   { id: 251, group: "Glute", name: "Romanian Deadlift" },
   { id: 252, group: "Glute", name: "Smith Machine Hip Thrust" },
   { id: 253, group: "Glute", name: "Single Leg Romanian Deadlift" },
   { id: 254, group: "Glute", name: "Standing Glute Kickback in Machine" },
   { id: 255, group: "Glute", name: "Standing Glute Push Down" },
   { id: 256, group: "Glute", name: "Step Up" },
   { id: 257, group: "Ab", name: "Ball Slams" },
   { id: 258, group: "Ab", name: "Cable Crunch" },
   { id: 259, group: "Ab", name: "Core Twist" },
   { id: 260, group: "Ab", name: "Crunch" },
   { id: 261, group: "Ab", name: "Dead Bug" },
   { id: 262, group: "Ab", name: "Dead Bug With Dumbbells" },
   { id: 263, group: "Ab", name: "Dragon Flag" },
   { id: 264, group: "Ab", name: "Hanging Knee Raise" },
   { id: 265, group: "Ab", name: "Hanging Leg Raise" },
   { id: 266, group: "Ab", name: "Hanging Sit-Up" },
   { id: 267, group: "Ab", name: "Hanging Windshield Wiper" },
   { id: 268, group: "Ab", name: "High to Low Wood Chop with Band" },
   { id: 269, group: "Ab", name: "High to Low Wood Chop with Cable" },
   { id: 270, group: "Ab", name: "Hollow Hold" },
   { id: 271, group: "Ab", name: "Horizontal Wood Chop with Band" },
   { id: 272, group: "Ab", name: "Horizontal Wood Chop with Cable" },
   { id: 273, group: "Ab", name: "Jackknife Sit-Up" },
   { id: 274, group: "Ab", name: "Kettlebell Plank Pull Through" },
   { id: 275, group: "Ab", name: "Kneeling Ab Wheel Roll-Out" },
   { id: 276, group: "Ab", name: "Kneeling Plank" },
   { id: 277, group: "Ab", name: "Kneeling Side Plank" },
   { id: 278, group: "Ab", name: "L-Sit" },
   { id: 279, group: "Ab", name: "Lying Leg Raise" },
   { id: 280, group: "Ab", name: "Lying Windshield Wiper" },
   { id: 281, group: "Ab", name: "Lying Windshield Wiper with Bent Knees" },
   { id: 282, group: "Ab", name: "Machine Crunch" },
   { id: 283, group: "Ab", name: "Mountain Climbers" },
   { id: 284, group: "Ab", name: "Oblique Crunch" },
   { id: 285, group: "Ab", name: "Oblique Sit-Up" },
   { id: 286, group: "Ab", name: "Plank" },
   { id: 287, group: "Ab", name: "Plank with Leg Lifts" },
   { id: 288, group: "Ab", name: "Side Plank" },
   { id: 289, group: "Ab", name: "Sit-Up" },
   { id: 290, group: "Calves", name: "Barbell Standing Calf Raise" },
   { id: 291, group: "Calves", name: "Donkey Calf Raise" },
   { id: 292, group: "Calves", name: "Eccentric Heel Drop" },
   { id: 293, group: "Calves", name: "Heel Raise" },
   { id: 294, group: "Calves", name: "Seated Calf Raise" },
   { id: 295, group: "Calves", name: "Standing Calf Raise" },
   { id: 296, group: "Forearms and Grip", name: "Barbell Wrist Curl" },
   {
      id: 297,
      group: "Forearms and Grip",
      name: "Barbell Wrist Curl Behind the Back",
   },
   { id: 298, group: "Forearms and Grip", name: "Bar Hang" },
   { id: 299, group: "Forearms and Grip", name: "Dumbbell Wrist Curl" },
   { id: 300, group: "Forearms and Grip", name: "Farmers Walk" },
   { id: 301, group: "Forearms and Grip", name: "Fat Bar Deadlift" },
   { id: 302, group: "Forearms and Grip", name: "Gripper" },
   { id: 303, group: "Forearms and Grip", name: "One-Handed Bar Hang" },
   { id: 304, group: "Forearms and Grip", name: "Plate Pinch" },
   { id: 305, group: "Forearms and Grip", name: "Plate Wrist Curl" },
   { id: 306, group: "Forearms and Grip", name: "Towel Pull-Up" },
   { id: 307, group: "Forearms and Grip", name: "Wrist Roller" },
   { id: 308, group: "Forearm Extensors", name: "Barbell Wrist Extension" },
   { id: 309, group: "Forearm Extensors", name: "Dumbbell Wrist Extension" },
   { id: 310, group: "Cardio", name: "Rowing Machine" },
   { id: 311, group: "Cardio", name: "Stationary Bike" },
   { id: 312, group: "Cardio", name: "Running" },
   { id: 313, group: "Cardio", name: "Swimming" },
   { id: 314, group: "Cardio", name: "Bicycling" },
   { id: 315, group: "Cardio", name: "Sport-Specific Training" },
];
